### ISSUE TITLE
excel2wiki.toolforge.org "Webservice request timed out"

### ISSUE THREAD

**Issue by denniz-j** [zanhecht/excel2wiki#1]
Hi,
I don't have a wikitech.wikimedia.org login, and getting one seemed slightly involved, so I'm trying to raise an issue here instead...

https://excel2wiki.toolforge.org/ is currently giving the following error...

Webservice request timed out

The tool responsible for the URL you have requested, https://excel2wiki.toolforge.org/, is taking too long to respond.
If you have reached this page from somewhere else...

This URI is managed by the [excel2wiki](https://toolsadmin.wikimedia.org/tools/id/excel2wiki) tool, maintained by [Ahecht](https://wikitech.wikimedia.org/wiki/User:Ahecht).

You may wish to notify the tool's maintainers (above) about the error.

If you maintain this tool

The web service for this tool is running but cannot be reached. Please check the error logs of your web service.

Thanks for this tool.
Dennis

**Comment by zanhecht** [comment]
Webservice restarted. Thanks for letting me know!
